<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <TargetPlatformMinVersion>7.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <LangVersion>preview</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <NoWarn>$(NoWarn);CA1416;CS0067</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\stopwatch.wav" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatformAttribute">
      <_Parameter1>Windows7.0</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
